### ISSUE TITLE
#7 Delete Service

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#10]
# Value Proposition

**As a** User 
**I want to** delete a Services 
**So that** I can make sure that outdated services will not be used anymore.

# Description

![Image](https://user-images.githubusercontent.com/101249132/184348228-588bfdaa-d0c6-4edd-823a-c8f7ad4154c5.png)

![Image](https://user-images.githubusercontent.com/101249132/184350013-a21732a5-bcca-4d8e-9ab0-44d43b715c74.png)

# Acceptance Criteria

- [ ] When a Service is clicked the User will be redirected on a new Page to see the Service
- [ ] The user gets to see the whole service Form
- [ ] There is a Delete Button displayed
- [ ] On click the Service will be deleted
- [ ] the user will be redirected on the Services Page

# Tasks

- [ ] Create a new feature Branch
- [ ] Create Delete Button
- [ ] On click delete the service
- [ ] Redirect the User on Services page

# Complexity

M

**Comment by j-eick** [comment]
"On click the Service will be deleted"
💭 I think you mean to say that "On click the **selected** Service will be deleted"?

"Redirect the User on Services page"
💭 By doing what? More specificity.
➡️ "Redirect the User to Services page upon clicking the delete-button"

**Comment by ahohnsen** [comment]
Hey Petros,

Your scribble contains elements which are not part of your app & user story yet (e.g. hamburger menu, profile picture). Please adjust your scribble.

Will the user need to confirm deleting the service or will it be deleted instantly? 🙂
