### ISSUE TITLE
#8 Menu Navigation Bar

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#11]
# Value Proposition

**As a** User 
**I want to** have a menu access point bar 
**So that** I can access the navigation and navigate to different pages inside the App

# Description

![Image](https://user-images.githubusercontent.com/101249132/184350780-b2062e8a-d4a5-4790-b853-91cebe2699b3.png)

# Acceptance Criteria

- [ ] A Menu access bar is Displayed on the Top of every Page
- [ ] At the Right side is a small rounded Default Picture/Logo
- [ ] At the left side is a "hamburger" icon     

# Tasks

- [ ] Create a new feature Branch
- [ ] Create Nav Bar
- [ ] Add Default Image on the Right
- [ ] Add a Hamburger Menu Icon on the left
- [ ] Create a Layout and add the Nav Bar to it, so it will displayed on each page

# Complexity

S

**Comment by ahohnsen** [comment]
Hey Petros,

I think it would be best to split this in two separate user stories. 1. the hamburger menu with already working links inside (it would be nice to see the open menu in an additional scribble) and 2. the profile picture with a profile page.
If you add the hamburger menu icon and the profile image and they do not have any function, this will add no value to the user.

**Comment by tsimvris** [comment]
CLOSED ISSUE AND MERGED ON ANOTHER
