### ISSUE TITLE
#8 Create Drawer menu

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#12]
# Value Proposition

**As a** User 
**I want to** have a Drawer Menü 
**So that** I can navigate to different pages inside the App

# Description

<img width="342" alt="Bildschirmfoto 2022-08-16 um 14 54 55" src="https://user-images.githubusercontent.com/101249132/184884667-e29203ac-5028-455f-a033-3060541ca5c4.png">

# Acceptance Criteria

- [x] A Menu access bar is Displayed on the Top of every Page
- [x] At the left side is a "hamburger" icon     
- [x] When the hamburger icon is clicked, a Side drawer Menü should be displayed
- [x]  On the Menu is every page displayed
- [x]  By clicking a page, the User will be redirected to the Page      
- [x] By clicking outside of the Menu, the Menu is closing 

# Tasks

- [x] Create a new feature Branch
- [x] Create Nav Bar
- [x] Add a Hamburger Menu Icon on the left
- [x] Create a Layout and add the Nav Bar to it, so it will displayed on each page
- [x] Create the "pop up " menu
- [x] Add Links to each Page
- [x] Find a way so that the menu is opening on click
- [x] Find a way so that the menu is closing if the user click somewhere outside of it
- [x] Find a Library , or code it on your own :-)

# Complexity

L

**Comment by ahohnsen** [comment]
Please see my comment under your previous user story. You should restructure these two user stories. The goal is to always add a fully functional feature. So you should add the hamburger menu icon together with the side drawer menu described here. 
The menu should only include links/icons for the pages you have already implemented (e.g. no logout button, no profile page button etc.) You can add these links later on once you really need them.

**Comment by ahohnsen** [comment]
Nice update - just take out the profile picture from the scribble & acceptance criteria as this should be part of a separate story.
