### ISSUE TITLE
#9 Add Profile Page

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#13]
# Value Proposition

**As a** User <br>
**I want to** have a Profile Page where i can enter my company's Data<br>
**So that** I can save them and generate Invoices later.

# Description

![Image](https://user-images.githubusercontent.com/101249132/184163020-91992d4d-97b7-40ff-b629-ce973e9ddc48.png)

# Acceptance Criteria

- [x] Display My Company's Logo
- [x] A change Picture button is displayed
- [x] An input field for the Company's name is displayed (label: "Company Name")
- [x] An input field for the Company's Adress is displayed (label: "Company Adress")
- [x] An input field for the Company's Postal Code is displayed (label: "Company ZIP")
- [x] An input field for the Company's City is displayed (label: "Company City")
- [x] An input field for the Company's Tax ID is displayed (label: "Company Tax ID")
- [x] All form fields are required
- [x] A submit button is displayed
- [x] After submitting the form the User is redirected in the Home Page

# Tasks

- [x]  Create a new feature Branch
- [x] Add our Logo as Default Logo Picture, before the user add his own
- [x] Add an "Change Picture" Button
- [x] Find a way so that the User can upload his own Logo
- [x] use the Styled Input Fields 5 times in the Form(Already created for another form)
- [x] Use the Styled Submit Button(Already created for another form)
- [x] Add state handling (with Zustand.js)
- [x] Add Persist for the localStorage in Zustand.js

# Complexity

XL

**Comment by A11yship** [comment]
Hey Petros,
the story looks good.
I think it would be helpful to add some validation to your form to make sure the user enters the right data.

**Comment by tsimvris** [comment]
Hey Hannah, the Form Validation is already created and used by the "add new Client" Form, and will be used here too cause it is the same form and input data.

**Comment by A11yship** [comment]
Ok
