### ISSUE TITLE
#2.5 Form Validation Rendering

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#16]
# Value Proposition

**As a** Admin <br>
**I want to** have the Form validation errors rendert<br>
**So that** the user understand , which input he filled incorrectly.

# Description

Display the Validation errors 

# Acceptance Criteria

🥇  Render the "add new client" Form validation errors 

# Tasks

- [x]  Create a new feature Branch
- [x]  read the React useForm hook Documentation
- [x]  find a way to render the error under the input field

# Complexity

M

**Comment by ahohnsen** [comment]
Hey Petros,

You have already closed this issue but I wanted to leave you some feedback for further user stories anyway 🙂 
I think you could have written the value proposition also from the perspective of the user:

> As a user
> I want to get visual feedback if I have filled the form incorrectly
> so that I will be able to submit the form successfully more quickly.

It would also have been nice to see a scribble with example error messages displayed. So it is easier to see where they should go and when they will be rendered e.g. if the user clicks on the submit button or as soon as the user types incorrect information into the input field.
