### ISSUE TITLE
#10 Add Buttons Tests

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#25]
# Value Proposition

**As a** Dev <br>
**I want to** have button tests<br>
**So that** I be sure that all my buttons are working properly.

# Acceptance Criteria

- [x] All the tests run successfully

# Tasks

- [x]  Create a new feature Branch
- [x] Write Tests for each Button
- [x] Run the Tests and check the results

# Complexity

M
