### ISSUE TITLE
#11 Add Form Tests

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#26]
# Value Proposition

**As a** Dev <br>
**I want to** have Form tests<br>
**So that** I be sure that all my Forms are working properly.

# Acceptance Criteria

- [ ] All the tests run successfully

# Tasks

- [ ]  Create a new feature Branch
- [ ] Write Tests for each Form
- [ ] Run the Tests and check the results

# Complexity

M
