### ISSUE TITLE
#13 Create invoices page and Invoice Form

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#29]
# Value Proposition

**As a** User 
**I want to** have a Invoice Page where i can see and generate new Invoices
**So that** I can collect my earnings from my Services.

# Description

![Image](https://user-images.githubusercontent.com/101249132/185743784-2a19f542-4dcc-442f-8686-20bd22fe77dd.png)

![Image](https://user-images.githubusercontent.com/101249132/185743793-e8b8d6c6-e028-4241-9904-fa5400c3ea10.png)

# Acceptance Criteria

- [x] A "Generate new Invoice" button is displayed
- [x] Per button click the user will be redirected the the "Generate Invoice Form" page
- [x] A Form with 5 input/dropdown Fields and a submit/generate button is displayed
- [x] A Dropdown for the Client is displayed (label: "Select your Client")
- [x] A Dropdown for the Service is displayed (label: "Select Service")
- [x] An input field for the Worked Hours is displayed (label: "Worked Hours")
- [x] An input field for the Price/Hour is displayed and has the default Price/Hour from the selected Service (label: "Price / Hour")
- [x] An input field for the Tax Key is displayed  and has the default Tax Key from the selected Service(label: "Tax Key")
- [x] All form fields are required
- [x] A submit button is displayed
- [x] On Submit a unique ID will be adviced on the generated Invoice
- [x] After submitting the form the User is redirected back in the Invoice Page
- [x] The generated Invoice is now rendered in the Recent Invoices

# Tasks

- [x] Create a new feature Branch
- [x] Create a Invoice Page
- [x] Create a Invoice Form Page
- [x] Create The Form
- [x] Get the States from Clients and Services , to be mapped on the Dropdowns
- [x] Validate the Form
- [x] save the Input Values with zustand
- [x] Redirect the user back to Invoice Page on Submit
- [x] Render the Recent Invoices with Client Name and Invoice Number

# Complexity

XL
