### ISSUE TITLE
#1 Add New Clients

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#3]
# Value Proposition

**As a** User 
**I want to** have a Clients Page where i can enter Information about my Clients
**So that** I can save them and edit them later.

# Description

![Image](https://user-images.githubusercontent.com/101249132/184343505-3b49a009-0952-4892-af29-961e0a5ab8a1.png)

![Image](https://user-images.githubusercontent.com/101249132/184343532-27837fca-14ea-4bef-8b02-cf1033aa3c7c.png)

# Acceptance Criteria

- [x] A "Add new Client" button is displayed
- [x] Per button click the user will be redirected in a new "Add new Client" Page
- [x] A Form with 5 input Fields and a submit button is displayed
- [x] An input field for the Company's name is displayed (label: "Company Name")
- [x] An input field for the Company's Adress is displayed (label: "Company Adress")
- [x] An input field for the Company's Postal Code is displayed (label: "Company ZIP")
- [x] An input field for the Company's City is displayed (label: "Company City")
- [x] An input field for the Company's Tax ID is displayed (label: "Company Tax ID")
- [x] All form fields are required
- [x] A unique ID will be generated for each Client
- [x] A submit button is displayed
- [x] After submitting the form the User is redirected in the Clients Page

# Tasks

- [x] Create a new feature Branch
- [x] Create a Clients Page
- [x] Create a Styled Button to add new Clients
- [x] Add this button on the Clients page
- [x] Create a "add new client" Page
- [x] Redirect the client with button click on the "add new client" Page
- [x] Create a Styled Input Field to be used 5 times in the Form
- [x] Create a Styled Submit Button
- [x] Create a form component and add five Styled input fields
- [x] Add the Styled submit button to the form
- [x] Add event.preventDefault() to the form submit
- [x] Redirect the User on form submit to the Clients Page
- [x] Add state handling (with Zustand.js)
- [x] Add a unique ID on each Client
- [x] Save the Input values with zustand
- [x] Add Persist for the localStorage in Zustand.js

# Complexity

L

**Comment by ahohnsen** [comment]
Hey Petros,

Nice job 🚀 I have a few suggestions:

**Comment by ahohnsen** [comment]
Hey Petros, 

Nice job 🚀 I have a few suggestions:

Scribble:
- Here it looks like you would use placeholder text inside the input fields instead of a label. However, in your Acceptance Criteria you are talking about labels. I strongly suggest label-elements for all your input fields. This should be also reflected in your scribble.

Acceptance Criteria:
- You do not need to describe what is visible in the scribble (e.g. A "Add new Client" button is displayed etc.), so you can shorten this a lot. We do want to describe what is NOT visible in the scribble e.g. if input fields are required, how the user can interact with the page etc. So these parts you should keep 👍🏼 

Tasks:
- Your task list is very long. The implementation of the localStorage should be done in a separate user story later on.

I also strongly recommend to implement the page with the button "add new client" later on. Right now, the user can only enter client data, so it would be best, if the user directly sees the form when loading the app. There is no need for the user to do another click to reach the form. Once you have implemented other functions, you can add a page where the user can decide which function he/she wants to use. 
So you would need to adjust the scribble , acceptance criteria and task list accordingly.

Additionally, it would be best to render the user data somewhere, so when the user clicks the submit-button a list or something similar should show the entered data. Otherwise this function has no real use for your user.

**Comment by tsimvris** [comment]
Hi Andrea,

Thanks for the Info.

The localStorage implementation is already done :)
I dont want to have the Form where the Client are being Rendered, so it is necessary to redirect in a new page to complete the Form and redirect back on Clients.

Thanks for the Info :)
