### ISSUE TITLE
#12 Add search in clients

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#30]
# Value Proposition

**As a** User 
**I want to** have to have a search function on the Clients Page
**So that** I can find my clients easier and faster without scrolling.

# Description

![Image](https://user-images.githubusercontent.com/101249132/185744345-ef7fb7eb-3cfd-4482-a337-2f8ab8c51b16.png)

# Acceptance Criteria

- [x] A "Search" field is displayed on the top of the Page
- [x] While typing you can see the clients that pass with your search coming up on the list
- [x] If i have a direct match it will appear on the top of the Clients list

# Tasks

- [x] Create a new feature Branch
- [x] Create a Search Field 
- [x] Implement the Search Function
- [x] Render the "wanted" client on the top of the other clients.

# Complexity

XL
