### ISSUE TITLE
#15 Login Auth

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#33]
# Value Proposition

**As a** Dev 
**I want to** have an authorisation system
**So that** the users can create an account and login with it.

# Description

![Image](https://user-images.githubusercontent.com/101249132/185782324-aed829aa-a368-467e-b159-af1149d41e87.png)

# Acceptance Criteria

- [x] A Login/Signup Page appears when you open the App
- [x] If the user has already an account can login and he will be redirected on the Homepage
- [x] If the user isn't registered , then he has to signup and then login to be redirected to the Homepage.
- [x] On Login the Auth-Sytem has to validate the credentials of the user if they are correct.
- [x] If the credentials are incorrect an Error will appear

# Tasks

- [x] Create a new feature Branch
- [x] Create Login / Signup Page
- [x] Implement Auth
- [x] Style the Auth Pages
- [x] Route the whole app based on Auth.

# Complexity

XL
