### ISSUE TITLE
#14 Chart.js in der Dashboard implementieren

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#34]
# Value Proposition

**As a** user 
**I want to** have a dashboard page
**So that** i can check my statistics about Invoices and my Clients

# Description

![Image](https://user-images.githubusercontent.com/101249132/185782612-6bffb4c2-b262-470b-bcc0-e1ec3ef97e5e.png)

# Acceptance Criteria

- [x] A bunch of Charts based on the Client and Invoice database are rendered on the Home Page

# Tasks

- [x] Create a new feature Branch
- [x] Create Dashboard page
- [x] Implement Chart.js
- [x] Create and Style the Charts 

# Complexity

XL
