### ISSUE TITLE
#16 Migrate localStorage users on MongoDB

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#39]
# Value Proposition

**As a** Dev 
**I want to** migrate the registered users from localStorage to my Databank in mongoDB
**So that**the user data will be globally accessible 

# Acceptance Criteria

- [x] The user credentials are no longer saved in localStorage
- [x] The user credentials are in a new MongoDB databank saved and globally reachable

# Tasks

- [x] Create a new feature Branch
- [x] Create Atlas mongoDB 
- [x] Implement mongoose
- [x] Implement MongoDB connection
- [x] Set the POST and SET functions

# Complexity

XL

**Comment by j-eick** [comment]
If you already know how you will realise your POST and SET functions, then maybe share a few more thoughts on that so participants can join your thought process.

Other than that. Nice! 🤌🏼

**Comment by tsimvris** [comment]
@j-eick i dont know but there is Google 😃
