### ISSUE TITLE
#2 Render Clients

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#4]
# Value Proposition

**As a** User 
**I want to** see a list of my clients alphabetically sorted
**So that** I can find them easier and edit them later.

# Description

![Image](https://user-images.githubusercontent.com/101249132/184345034-78a8d4c0-6f6d-4a43-a754-d2d33f1d4a4a.png)

# Acceptance Criteria

- [x] Right down from the "Add New Client" button is a list with all the Clients displayed.
- [x] The rendered list have to be alphabetically sorted.
- [x] Preferred will be a Phonebook styled list.
- [x] The unique client ID will not be displayed in any time

# Tasks

- [x] Create a new feature Branch
- [x] Create a section where the clients will be displayed at
- [x] map() the clients
- [x] sort() the clients alphabetically
- [x] Create a Phonebook-styled list and render the Clients

# Complexity

L

**Comment by ahohnsen** [comment]
Hey Petros,

Nicely done! 👍🏼 I have a few suggestions/thoughts:

Value Proposition:

> As a User
I want to see a list of my clients alphabetically sorted
So that I can find them easier and edit them later.

- I think sorting them alphabetically so that the user can find the clients easier is a valid reason. I would erase the editing-part as this has not much to do with this functionality.

Scribble:
- As you do not implement the editing function in this user story, I suggest to erase the edit-button from your scribble. 
- As well, you are only displaying the names of the clients in the list. I am wondering where all the rest of the data will be rendered as in your previous user story the user is able to type in a lot of details for each client. I would suggest to render a card for each client with all information about this client.
- Your scribble (and acceptance criteria) do not show/describe how the user can reach the client list and the form to enter a new client. To make things easier, you can display both on one page first and then separate the form and list later on - but of course you will need to adjust your scribble either way 🙂 

Acceptance Criteria:
- Please see my comments on your previous user story.
- It is not really clear what you mean by:  _Preferred will be a Phonebook styled list._ - I would recommend to be a bit more specific so that other developers will also be able to understand your user story completely.

**Comment by tsimvris** [comment]
Hi Andrea,

The rest Client Info will be rendered on click, if the user click on a single Client.

**Comment by ahohnsen** [comment]
Please keep in mind that also other developers should be able to code your app following your user stories. So if there is a detailed view of the client information, it should be visible in the scribble and described in the acceptance criteria e.g. "By clicking on a client name detailed information about the client will be shown underneath the client name"
