### ISSUE TITLE
#3 Edit Clients

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#5]
# Value Proposition

**As a** User 
**I want to** edit my clients infos
**So that** I can have an UpToDate list of my clients anytime.

# Description

![Image](https://user-images.githubusercontent.com/101249132/184345223-374939d5-3424-4aec-b238-697fd541cef8.png)

![Image](https://user-images.githubusercontent.com/101249132/184345310-609f0d9f-6285-42e9-89b6-eaa5e15b94fa.png)

# Acceptance Criteria

- [x] On each Client is an "Edit" button displayed
- [x] On click the user can edit the Client infos 
- [x] The Edit Form is the Same with the "Create new client" form
- [x] Instead of a "Submit" button a "Save" button will be displayed
- [x] On save the User is redirected on the Clients page

# Tasks

- [x] Create a new feature Branch
- [x] Create Edit Page
- [x] User the Form for create with a save button instead
- [x] Show the user the "old" client data
- [x] The unique client ID will not be displayed in any time
- [x] On save , update the client data
- [x] Redirect the User on the Client Page

# Complexity

L
