### ISSUE TITLE
#4 Add new Services and Render them

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#6]
# Value Proposition

**As a** User 
**I want to** have a Services Page where i can enter Information about Services i offer
**So that** I can save them and see them.

# Description

![Image](https://user-images.githubusercontent.com/101249132/184346827-04ac16e8-fec6-4149-b1c0-4ebfa8dc41a6.png)

![Image](https://user-images.githubusercontent.com/101249132/184346857-17bd6f89-3efe-4cb3-829b-79fb36482b79.png)
![Image](https://user-images.githubusercontent.com/101249132/184347254-ed4c72db-78a1-4db7-ad75-8a6759c704e9.png)

# Acceptance Criteria

- [x] Per button click the user will be redirected in a new "Add new Service" Page
- [x] All form fields are required
- [x] A submit button is displayed
- [x] After submitting the form the User is redirected in the Services Page
- [x] Right down from the "Add New Service" button is a list where all the Services are displayed.

# Tasks

- [x] Create a new feature Branch
- [x] Create a Services Page
- [x] Create a Styled Button to add new Service
- [x] Add this button on the Service page
- [x] Create a "add new Service" Page
- [x] Redirect the client with button click on the "add new Service" Page
- [x] Use the Styled Inputs created for the "Add new Client" form earlier
- [x] Use the already created  "Styled Submit Button"
- [x] Create a form component and add four Styled input fields
- [x] Add the Styled submit button to the form
- [x] Add event.preventDefault() to the form submit
- [x] Redirect the User on form submit to the Service Page
- [x] Add state handling (with Zustand.js)
- [x] Save the Input values with zustand
- [x] Add Persist for the localStorage in Zustand.js
- [x] Create a section where the Services will be displayed at
- [x] map() the Services and Render
- [x] Style the Rendered Services

# Complexity

L

**Comment by ahohnsen** [comment]
Hey Petros,

Good job 💪🏼 

It would be nice to also have a scribble of your service page and not only the form.

> 
 After submitting the form the User is redirected in the Services Page

The user is redirected but what happens with the entered data (services)? Will they be shown as a list on the service page?

**Comment by tsimvris** [comment]
Hi Andrea,

The Data will not be visible in this moment except in localStorage, the rendering is on the next User Story
