### ISSUE TITLE
#5 Render Services

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#7]
# Value Proposition

**As a** User 
**I want to** see a list of my Services
**So that** I can find them easier and edit them later.

# Description

![Image](https://user-images.githubusercontent.com/101249132/184347254-ed4c72db-78a1-4db7-ad75-8a6759c704e9.png)

# Acceptance Criteria

- [ ] Right down from the "Add New Service" button is a list where all the Services are displayed.

# Tasks

- [ ] Create a new feature Branch
- [ ] Create a section where the Services will be displayed at
- [ ] map() the Services and Render
- [ ] Style the Rendered Services

# Complexity

S

**Comment by ahohnsen** [comment]
Hey Petros,

Please see my comment on your previous user story. I would join these two user stories together, as it makes not so much sense to let the user enter data which he/she cannot see afterwards 🙂

**Comment by tsimvris** [comment]
Hi Andrea,

Thanks for the Feedback, i merged the two stories into 1
