### ISSUE TITLE
#5 Show Services Details

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#8]
# Value Proposition

**As a** User 
**I want to** preview my Services infos/details
**So that** I can check if the details are upToDate.

# Description

![Image](https://user-images.githubusercontent.com/101249132/184348228-588bfdaa-d0c6-4edd-823a-c8f7ad4154c5.png)

![Image](https://user-images.githubusercontent.com/101249132/184348250-10122982-ce76-4991-bb81-638f78b11b87.png)

# Acceptance Criteria

- [ ] When a Service is clicked the User will be redirected on a new Page to see the Service
- [ ] The user gets to see the whole service Form(4 Items)
- [ ] There is a Edit Button displayed

# Tasks

- [ ] Create a new feature Branch
- [ ] Create Edit Page
- [ ] Use the Form for create with a Edit button instead
- [ ] Show the user the actual Service data

# Complexity

M

**Comment by j-eick** [comment]
One minor point: 
"The user gets to see the whole service Form"

➡️ "The user gets to see the whole service Form (here: 4 items)"

💭 This way reviewers know exactly what you mean.

**Comment by ahohnsen** [comment]
Hey Petros,

I would suggest to split this in two user stories: 

1. detail view of the services
2. edit function from services

These are two different functionalities which do not need to be implemented together. In this way you can keep your user stories smaller.

**Comment by tsimvris** [comment]
This is only the detail View of the Services, the edit function is seperated
