### ISSUE TITLE
#6 Edit Services

### ISSUE THREAD

**Issue by tsimvris** [tsimvris/capstone-project#9]
# Value Proposition

**As a** User 
**I want to** edit my Services infos
**So that** I can change the Details or the Price of a Service .

# Description

![Image](https://user-images.githubusercontent.com/101249132/184349003-8f332617-c138-4470-ae90-d3378e346b83.png)

![Image](https://user-images.githubusercontent.com/101249132/184349011-05e85a37-8e35-4317-b77f-96fb5f44febc.png)

# Acceptance Criteria

- [ ] When a User clicks the Edit Button he gets to edit the Service infos
- [ ] The user gets to see the whole service Form
- [ ] There is a Save Button displayed
- [ ] On Save the User is redirected to the Services Page

# Tasks

- [ ] Create a new feature Branch
- [ ] Use the Form for create with a Save button instead
- [ ] Show the user the actual Service data
- [ ] Track changes between old and new data
- [ ] Save on Change the state.
- [ ] Redirect the user on Save to the Service Page

# Complexity

M

**Comment by j-eick** [comment]
Looks good 👌🏼
I think a bit more specificity on the formulation wouldn't hurt.

**Comment by ahohnsen** [comment]
I like that you are reusing the form from your create functionality :) 

I think you can be a bit more specific in your acceptance criteria. As right now, it is not clear that the previous data will be prefilled in the edit-form.

**Comment by tsimvris** [comment]
Hi Andrea,

In Task 3  Show the user the actual Service data is specified that the user gets to see the "old" data
